// Diving + DivingHQ jargon glossary.
//
// Every term is short and flat, one definition per term, no
// disambiguation. Match is case-insensitive and ignores trailing
// punctuation. Add to this file as new vocabulary surfaces in the
// UI, but keep definitions under ~120 chars so they still fit in
// the JargonTip popover without scrolling.

const TERMS = {
  // Scoring + judging
  DD:           "Degree of Difficulty — a per-dive multiplier (1.2–4.8) applied to the trimmed sum of judges' scores.",
  ROC:          "Round of competition — one pass through the entire dive list (e.g. round 3 of 5).",
  trim:         "World Aquatics rule that drops the highest and lowest judge scores before summing the remaining halves.",
  balk:         "A diver starts a takeoff but stops or aborts. Counts as a failed dive — score is zero and the dive cannot be repeated.",
  redive:       "When the referee allows a diver to re-attempt the same dive (e.g. equipment failure or balk overruled).",
  failed:       "A dive scored as 0 — incorrect position, wrong somersault count, or refusal to dive within 1 minute.",

  // Event lifecycle
  upcoming:     "Status: event is published and accepting entries. Not live yet.",
  live:         "Status: event is in progress — judges scoring, scoreboard streaming.",
  completed:    "Status: event finalised. Public scoreboard shows recap; results in the archive.",
  setup:        "Status: event being configured — roster, judges, dive list. Not visible to spectators.",

  // World Aquatics
  WA:           "World Aquatics — the international governing body for aquatic sports, source of the official rule book + scoring formula.",
  "WA TE":      "World Aquatics Team Event — synchronised event scored as a team rather than per individual diver.",
  panel:        "The set of judges (typically 5 or 7) who score each dive.",
  referee:      "The senior official who oversees the panel, rules on balks/redives, and approves final results.",

  // DivingHQ-specific
  "Sign Off":   "Pre-meet referee approval step. The referee enters a one-time code generated by Control Room to mark the panel + roster ready for live.",
  "Control Room": "The operator surface that drives a live meet — start, advance, hold, finalise.",
  "Meet Manager": "The pre-meet operator surface — create event, edit roster, assign judges.",
  "Pulse strip": "The dashboard's live + upcoming + pending counter strip across the top.",
  "Audit Log":  "Per-event timeline of every score insert, update, and delete with actor + IP + reason.",
  "active diver": "The diver currently performing — pinned to the top of the scoreboard until the next advance.",
  "meet hold":  "An operator-initiated pause on a live event. Scoring is blocked until the hold is cleared.",

  // Roles
  "org admin":  "Federation-level admin — manages users, roles, clubs, teams, audit log.",
  "meet manager": "Per-meet operator — creates and runs a single event without federation-wide privileges.",
  diver:        "Competitor. Owns their dive list and history; can request coach links.",
  coach:        "Linked to one or more divers; sees their templates, history, analytics.",
  judge:        "Submits scores during live events. Read-only access outside of judging.",
  spectator:    "Anonymous public viewer of scoreboards and final results.",

  // Records
  PB:           "Personal Best — your highest total for a given dive code + position + board.",
  "club record": "The highest total any member of a club has scored for a given dive code + position + board.",
  "federation record": "The highest total any diver in the federation has scored for a given dive code + position + board.",
}

// Case-insensitive lookup, tolerates trailing punctuation
// ("DD?" or "DD."). Returns null when not found.
export function lookupTerm(raw) {
  if (!raw) return null
  const cleaned = String(raw).replace(/[?.,!;:]+$/, '').trim()
  if (!cleaned) return null
  // Try exact + case-insensitive
  if (TERMS[cleaned]) return TERMS[cleaned]
  const lower = cleaned.toLowerCase()
  for (const [k, v] of Object.entries(TERMS)) {
    if (k.toLowerCase() === lower) return v
  }
  return null
}

export function allTerms() {
  return { ...TERMS }
}
