// Unit tests for lib/idempotency.js + lib/idempotency-sweeper.js.
//
// Pure JS, no Postgres. The pool is a hand-rolled mock that records
// queries + returns canned responses. This file verifies:
//
//   * canonicalise() is deterministic across key orderings.
//   * hashPayload() collides only on semantically-equal payloads.
//   * isValidUuidV4() rejects malformed inputs.
//   * httpMiddleware: cache miss → next(), cache hit → replay,
//     owner mismatch → 403, payload mismatch → 422, no key → next().
//   * socketCheck: same shape as middleware but for non-HTTP callers.
//   * sweeper.sweep() issues the DELETE with the right interval.
//
// Integration with a real Postgres lives in
// test/idempotency.integration.test.js (next commit, alongside
// wiring submit_score).

const { test } = require("node:test");
const assert = require("node:assert/strict");

const createIdempotency = require("../lib/idempotency");
const { hashPayload, isValidUuidV4, canonicalise } = createIdempotency;
const sweeper = require("../lib/idempotency-sweeper");

// ---- Mock pool ------------------------------------------------
// Records every query for assertions. queue is the response stack:
// each .query() pops the next entry. Pre-load it with the expected
// reply shape.
function makePool() {
  const calls = [];
  const queue = [];
  return {
    calls,
    queue,
    enqueue(response) { queue.push(response); },
    async query(sql, params) {
      calls.push({ sql, params });
      if (queue.length === 0) {
        throw new Error(`Mock pool: no canned response for query (${calls.length} so far)`);
      }
      const next = queue.shift();
      if (next instanceof Error) throw next;
      return next;
    },
  };
}

// ---- canonicalise / hashPayload -------------------------------

test("canonicalise sorts object keys deterministically", () => {
  const a = canonicalise({ b: 2, a: 1, c: 3 });
  const b = canonicalise({ c: 3, a: 1, b: 2 });
  assert.deepEqual(a, b);
  assert.deepEqual(Object.keys(a), ["a", "b", "c"]);
});

test("canonicalise recurses through nested objects", () => {
  const a = canonicalise({ outer: { y: 2, x: 1 } });
  const b = canonicalise({ outer: { x: 1, y: 2 } });
  assert.deepEqual(a, b);
  assert.deepEqual(Object.keys(a.outer), ["x", "y"]);
});

test("canonicalise preserves array order", () => {
  // Arrays are ordered by intent — don't sort them.
  const a = canonicalise([3, 1, 2]);
  assert.deepEqual(a, [3, 1, 2]);
});

test("hashPayload returns same Buffer for key-reordered objects", () => {
  const h1 = hashPayload({ a: 1, b: 2 });
  const h2 = hashPayload({ b: 2, a: 1 });
  assert.ok(Buffer.isBuffer(h1));
  assert.equal(h1.length, 32);  // sha256 = 32 bytes
  assert.ok(h1.equals(h2));
});

test("hashPayload returns different Buffer for different content", () => {
  const h1 = hashPayload({ score: 8.0 });
  const h2 = hashPayload({ score: 8.5 });
  assert.ok(!h1.equals(h2));
});

test("hashPayload handles null + undefined gracefully", () => {
  // null and undefined collapse to the same empty-object hash via
  // canonicalise's `value || {}` fallback. Caller shouldn't pass
  // either, but the helper doesn't blow up.
  const h1 = hashPayload(null);
  const h2 = hashPayload(undefined);
  const h3 = hashPayload({});
  assert.ok(h1.equals(h3));
  assert.ok(h2.equals(h3));
});

// ---- isValidUuidV4 --------------------------------------------

test("isValidUuidV4 accepts canonical UUID v4 strings", () => {
  // Generated by Node's crypto.randomUUID() which produces v4.
  assert.ok(isValidUuidV4("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d"));
  assert.ok(isValidUuidV4("A3F1C8D2-4B6E-4A8F-9D2C-1E3F5A7B9C0D"));  // upper OK
});

test("isValidUuidV4 rejects malformed inputs", () => {
  // Wrong version (v1)
  assert.ok(!isValidUuidV4("a3f1c8d2-4b6e-1a8f-9d2c-1e3f5a7b9c0d"));
  // Wrong variant
  assert.ok(!isValidUuidV4("a3f1c8d2-4b6e-4a8f-1d2c-1e3f5a7b9c0d"));
  // Truncated
  assert.ok(!isValidUuidV4("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c"));
  // Non-hex
  assert.ok(!isValidUuidV4("g3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d"));
  // Empty / null / undefined / non-string
  assert.ok(!isValidUuidV4(""));
  assert.ok(!isValidUuidV4(null));
  assert.ok(!isValidUuidV4(undefined));
  assert.ok(!isValidUuidV4(12345));
});

// ---- HTTP middleware ------------------------------------------
// Mock req/res that capture the response. Mimics the contract
// Express middleware sees: req.get(), req.body, req.user;
// res.status(), res.json(), res.set().
function makeMockReqRes({ headers = {}, body = {}, user = null } = {}) {
  let statusCode = 200;
  const setHeaders = {};
  const sentBody = { value: null };

  const req = {
    get(name) {
      const lower = name.toLowerCase();
      for (const k of Object.keys(headers)) {
        if (k.toLowerCase() === lower) return headers[k];
      }
      return undefined;
    },
    body,
    user,
  };

  const res = {
    status(code) { statusCode = code; return res; },
    set(name, value) { setHeaders[name] = value; return res; },
    json(body) { sentBody.value = body; return res; },
    get statusCode() { return statusCode; },
    set statusCode(v) { statusCode = v; },
    get setHeaders() { return setHeaders; },
    get sentBody() { return sentBody.value; },
  };

  return { req, res };
}

test("httpMiddleware: no idempotency_key → next() with no DB call", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({ user: { id: "u1" } });
  let nextCalled = false;
  await idem.httpMiddleware("action")(req, res, () => { nextCalled = true; });
  assert.ok(nextCalled);
  assert.equal(pool.calls.length, 0);
});

test("httpMiddleware: invalid UUID v4 → 400, no DB call", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": "not-a-uuid" },
    user: { id: "u1" },
  });
  let nextCalled = false;
  await idem.httpMiddleware("action")(req, res, () => { nextCalled = true; });
  assert.equal(res.statusCode, 400);
  assert.ok(res.sentBody.error.includes("UUID v4"));
  assert.equal(pool.calls.length, 0);
  assert.ok(!nextCalled);
});

test("httpMiddleware: no auth + key → 401, no DB call", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d" },
  });
  await idem.httpMiddleware("action")(req, res, () => {});
  assert.equal(res.statusCode, 401);
  assert.equal(pool.calls.length, 0);
});

test("httpMiddleware: cache miss → next(); response captured on the way out", async () => {
  const pool = makePool();
  pool.enqueue({ rows: [] });           // lookup: not found
  pool.enqueue({ rows: [], rowCount: 0 });  // insert: ON CONFLICT DO NOTHING returns 0
  const idem = createIdempotency({ pool });
  const key = "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d";
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": key },
    body: { score: 8.0 },
    user: { id: "u1" },
  });
  let nextCalled = false;
  await idem.httpMiddleware("submit_score")(req, res, () => { nextCalled = true; });
  assert.ok(nextCalled);

  // Handler responds.
  res.json({ ok: true, id: "score-123" });
  // Cache write is fire-and-forget; await a microtask for it to land.
  await new Promise((r) => setImmediate(r));
  assert.equal(pool.calls.length, 2);
  assert.ok(pool.calls[0].sql.startsWith("SELECT"));
  assert.ok(pool.calls[1].sql.startsWith("INSERT"));
  assert.equal(pool.calls[1].params[0], key);
  assert.equal(pool.calls[1].params[1], "u1");
  assert.equal(pool.calls[1].params[2], "submit_score");
});

test("httpMiddleware: cache hit, same user, same payload → replay", async () => {
  const cachedHash = hashPayload({ score: 8.0 });
  const pool = makePool();
  pool.enqueue({
    rows: [{
      user_id: "u1",
      request_hash: cachedHash,
      response_status: 200,
      response_body: { ok: true, id: "score-123" },
    }],
  });
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d" },
    body: { score: 8.0 },
    user: { id: "u1" },
  });
  let nextCalled = false;
  await idem.httpMiddleware("submit_score")(req, res, () => { nextCalled = true; });
  assert.ok(!nextCalled);
  assert.equal(res.statusCode, 200);
  assert.deepEqual(res.sentBody, { ok: true, id: "score-123" });
  assert.equal(res.setHeaders["X-Idempotent"], "replay");
});

test("httpMiddleware: cache hit, different user → 403", async () => {
  const cachedHash = hashPayload({ score: 8.0 });
  const pool = makePool();
  pool.enqueue({
    rows: [{
      user_id: "someone-else",
      request_hash: cachedHash,
      response_status: 200,
      response_body: { ok: true },
    }],
  });
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d" },
    body: { score: 8.0 },
    user: { id: "u1" },
  });
  await idem.httpMiddleware("submit_score")(req, res, () => {});
  assert.equal(res.statusCode, 403);
  assert.ok(res.sentBody.error.includes("different user"));
});

test("httpMiddleware: cache hit, same user, different payload → 422", async () => {
  const cachedHash = hashPayload({ score: 8.0 });  // cached
  const pool = makePool();
  pool.enqueue({
    rows: [{
      user_id: "u1",
      request_hash: cachedHash,
      response_status: 200,
      response_body: { ok: true },
    }],
  });
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d" },
    body: { score: 8.5 },  // different from cached
    user: { id: "u1" },
  });
  await idem.httpMiddleware("submit_score")(req, res, () => {});
  assert.equal(res.statusCode, 422);
  assert.ok(res.sentBody.error.includes("different payload"));
});

test("httpMiddleware: pool lookup error → fall through to handler", async () => {
  const pool = makePool();
  pool.enqueue(new Error("connection refused"));
  const idem = createIdempotency({ pool });
  const { req, res } = makeMockReqRes({
    headers: { "X-Idempotency-Key": "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d" },
    body: { score: 8.0 },
    user: { id: "u1" },
  });
  let nextCalled = false;
  await idem.httpMiddleware("submit_score")(req, res, () => { nextCalled = true; });
  assert.ok(nextCalled);
  // Handler runs normally; no replay header.
  assert.equal(res.setHeaders["X-Idempotent"], undefined);
});

test("httpMiddleware: body idempotency_key works as fallback to header", async () => {
  const pool = makePool();
  pool.enqueue({ rows: [] });
  pool.enqueue({ rows: [], rowCount: 0 });
  const idem = createIdempotency({ pool });
  const key = "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d";
  const { req, res } = makeMockReqRes({
    body: { idempotency_key: key, score: 8.0 },
    user: { id: "u1" },
  });
  let nextCalled = false;
  await idem.httpMiddleware("submit_score")(req, res, () => { nextCalled = true; });
  assert.ok(nextCalled);
  assert.equal(pool.calls[0].params[0], key);
});

// ---- socketCheck / socketStore --------------------------------

test("socketCheck: no key → null", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  const r = await idem.socketCheck(null, "u1", hashPayload({}));
  assert.equal(r, null);
  assert.equal(pool.calls.length, 0);
});

test("socketCheck: invalid UUID → error result", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  const r = await idem.socketCheck("not-a-uuid", "u1", hashPayload({}));
  assert.equal(r.error, "invalid_idempotency_key");
  assert.equal(r.status, 400);
});

test("socketCheck: no userId → auth_required error", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  const r = await idem.socketCheck("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d", null, hashPayload({}));
  assert.equal(r.error, "auth_required");
  assert.equal(r.status, 401);
});

test("socketCheck: cache miss → null", async () => {
  const pool = makePool();
  pool.enqueue({ rows: [] });
  const idem = createIdempotency({ pool });
  const r = await idem.socketCheck("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d", "u1", hashPayload({ x: 1 }));
  assert.equal(r, null);
});

test("socketCheck: cache hit returns response body", async () => {
  const hash = hashPayload({ score: 8.0 });
  const pool = makePool();
  pool.enqueue({
    rows: [{
      user_id: "u1",
      request_hash: hash,
      response_status: 200,
      response_body: { score_id: "abc" },
    }],
  });
  const idem = createIdempotency({ pool });
  const r = await idem.socketCheck("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d", "u1", hash);
  assert.equal(r.response_status, 200);
  assert.deepEqual(r.response_body, { score_id: "abc" });
});

test("socketStore: writes to idempotency_keys", async () => {
  const pool = makePool();
  pool.enqueue({ rowCount: 1 });
  const idem = createIdempotency({ pool });
  const hash = hashPayload({ score: 8.0 });
  idem.socketStore("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d", "u1", "submit_score", hash, 200, { score_id: "abc" });
  await new Promise((r) => setImmediate(r));
  assert.equal(pool.calls.length, 1);
  assert.ok(pool.calls[0].sql.startsWith("INSERT INTO idempotency_keys"));
  assert.equal(pool.calls[0].params[0], "a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d");
  assert.equal(pool.calls[0].params[1], "u1");
  assert.equal(pool.calls[0].params[2], "submit_score");
});

test("socketStore: no-op when key or userId missing", async () => {
  const pool = makePool();
  const idem = createIdempotency({ pool });
  idem.socketStore(null, "u1", "x", Buffer.alloc(32), 200, {});
  idem.socketStore("a3f1c8d2-4b6e-4a8f-9d2c-1e3f5a7b9c0d", null, "x", Buffer.alloc(32), 200, {});
  await new Promise((r) => setImmediate(r));
  assert.equal(pool.calls.length, 0);
});

// ---- Sweeper --------------------------------------------------

test("sweeper.sweep deletes rows older than 72 hours", async () => {
  const pool = makePool();
  pool.enqueue({ rowCount: 5 });
  // Re-init the sweeper's pool by calling start() then stop().
  // We don't want the interval running during the test, so call
  // stop() immediately after.
  sweeper.start({ pool, intervalMs: 999999999 });
  sweeper.stop();
  // The start() call also fires an initial sweep; that consumed
  // our queue entry. Re-queue + sweep manually for the assertion.
  pool.enqueue({ rowCount: 5 });
  const deleted = await sweeper.sweep();
  // Two sweep calls happened (one from start, one manual). Both
  // returned 5; we assert the manual one.
  assert.equal(deleted, 5);
  // Check the DELETE SQL shape.
  const lastCall = pool.calls[pool.calls.length - 1];
  assert.ok(lastCall.sql.includes("DELETE FROM idempotency_keys"));
  assert.ok(lastCall.sql.includes("created_at <"));
  assert.equal(lastCall.params[0], "72");
});

test("sweeper.start is idempotent", () => {
  const pool = makePool();
  pool.enqueue({ rowCount: 0 });
  sweeper.start({ pool, intervalMs: 999999999 });
  // Second start() should not throw or schedule again.
  sweeper.start({ pool, intervalMs: 999999999 });
  sweeper.stop();
  // We can't directly assert "only one interval registered" without
  // poking internals, but the lack of an error is the contract.
});
